import './globals.css'
import { Inter } from 'next/font/google'
import ResponsiveAppBar from './components/AppBar'
import { GlobalProvider } from './providers/GlobalContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <GlobalProvider>
          <ResponsiveAppBar></ResponsiveAppBar>
          {children}
        </GlobalProvider>
      </body>
    </html>
  )
}
